export const REQUEST_TAGS = 'REQUEST_TAGS';
export const REQUEST_TAGS_SUCCESS = 'REQUEST_TAGS_SUCCESS';
export const REQUEST_TAGS_FAILURE = 'REQUEST_TAGS_FAILURE';
export const ADD_TAG = 'ADD_TAG';
export const REMOVE_TAG = 'REMOVE_TAG';
